server:
  port: 30000


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5t6sDt5HzTnTqWmvQrbn
      secret-key: obwRzPB95OfnpB2bvPuAHo1mFbB2Kt
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: gulimall-buck-just
      host: https://dfsns.market.alicloudapi.com
      path: /data/send_sms
      method: POST
      appcode: 0c9de66de3a84416b9400a9dbdddb202

      # 短信二
      url: https://smssend.shumaidata.com/sms/send

  application:
    name: gulimall-third-paty



